apiVersion: v2
name: huginn
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
# this is not the real version, it looks via git shas?
appVersion: 1.16.0

dependencies:
- name: postgresql
  version: "8.7.3"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
